spring:
  application:
    name: r2dbc-proxy-examples
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics
